#!/bin/sh

set -eu

MARIADB_ROOT_PW=$1

# Allow the dodgy mysql_secure_installation script to find the server socket
ln -s /var/lib/mysql/mysql.sock /var/run/mysqld/mysqld.sock

# Run the installation securing script
/usr/bin/mariadb-secureinstallation "$MARIADB_ROOT_PW"

# Finally, grant access to off-container connections
GRANT="GRANT ALL ON *.* to root@'%' IDENTIFIED BY '${MARIADB_ROOT_PW}';\
       FLUSH PRIVILEGES;"
echo "$GRANT" | mysql -u root --password="$MARIADB_ROOT_PW" mysql

echo "---> MariaDB root password successfully set" >&2
